import { Category, SpaceType } from '../enums';

export type Accommodation = {
  title: string;
  description?: string;
  main_cover_image?: string;
  internal_images?: string[];
  is_active?: boolean;
  price_per_night?: number;
  cleaning_fee?: number;
  discount?: boolean;
  room_count?: number;
  bed_count?: number;
  bathroom_count?: number;
  guest_capacity?: number;
  category?: Category;
  space_type?: SpaceType;
  address?: string;
  city?: string;
  neighborhood?: string;
  postal_code?: string;
  uf?: string;
  wifi?: boolean;
  tv?: boolean;
  kitchen?: boolean;
  washing_machine?: boolean;
  parking_included?: boolean;
  air_conditioning?: boolean;
  pool?: boolean;
  jacuzzi?: boolean;
  grill?: boolean;
  private_gym?: boolean;
  beach_access?: boolean;
  smoke_detector?: boolean;
  fire_extinguisher?: boolean;
  first_aid_kit?: boolean;
  outdoor_camera?: boolean;
  coverOriginalName?: string;
};
