# Generated by Django 5.1.3 on 2024-11-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertylisting',
            old_name='registered_users',
            new_name='registered_user_bookings',
        ),
    ]
