# Generated by Django 5.1.3 on 2024-11-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertylisting',
            name='complement',
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='uf',
            field=models.CharField(blank=True, default='Not informed', max_length=10),
        ),
    ]
