# Generated by Django 5.1.1 on 2024-09-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodations',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='accommodations',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
