# Generated by Django 5.1.1 on 2024-09-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_name_accommodations_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_holder', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('agency_code', models.CharField(max_length=50)),
                ('account_type', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
    ]
