# Generated by Django 5.1.1 on 2024-10-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_useraccount_authenticated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='verification_token',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
