# Generated by Django 5.1.3 on 2024-11-25 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_propertylisting_complement_propertylisting_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='consecutive_days_limit',
            field=models.IntegerField(blank=True, help_text='Número de dias consecutivos permitido.', null=True),
        ),
    ]
