# Generated by Django 5.1.3 on 2024-11-27 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_registered_user_bookings_propertylisting_registered_bookings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertylisting',
            old_name='registered_bookings',
            new_name='registered_user_bookings',
        ),
    ]
