# Generated by Django 5.1.3 on 2024-11-25 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_propertylisting_consecutive_days_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='cleaning_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='registered_bookings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='propertylisting',
            name='registered_user_bookings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='registered_accommodations_bookings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
