# Generated by Django 5.1.1 on 2024-09-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_bankaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='main_cover',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
