# Generated by Django 5.1.3 on 2024-11-25 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_propertylisting_cleaning_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='discount',
            field=models.BooleanField(default=False),
        ),
    ]
