# Generated by Django 5.1.1 on 2024-09-28 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_accommodations_main_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodations',
            name='bank_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='data.bankaccount'),
        ),
    ]
