# Generated by Django 5.1.3 on 2024-11-25 08:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_propertylisting_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteProperty',
            fields=[
                ('id_favorite_property', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.propertylisting')),
                ('user_favorite_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user_favorite_property', 'accommodation'), name='unique_user_accommodation_favorite')],
            },
        ),
    ]
