# Generated by Django 5.1.1 on 2024-11-11 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_useraccount_registered_accommodations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='cpf',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
