# Generated by Django 5.1.1 on 2024-09-29 18:08

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_alter_accommodations_accommodated_guests_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Accommodations",
            new_name="Accommodation",
        ),
        migrations.RenameField(
            model_name="accommodation",
            old_name="property",
            new_name="property_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=data.models.upload_image
            ),
        ),
    ]
