# Generated by Django 5.1.3 on 2024-11-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='user_comment',
        ),
    ]
