# Generated by Django 5.1.3 on 2024-11-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_rename_user_review_user_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='average_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
