# Generated by Django 5.1.1 on 2024-09-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='internal_images',
            field=models.FileField(blank=True, null=True, upload_to='internal_images/'),
        ),
    ]
