# Generated by Django 5.1.3 on 2024-11-22 08:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_propertylisting_average_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='user_booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='id_booking',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='registered_bookings',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
