# Generated by Django 5.1.3 on 2024-11-22 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_rename_user_booking_user_booking_remove_booking_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_price',
            new_name='price',
        ),
    ]
