# Generated by Django 5.1.3 on 2024-11-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_rename_total_price_booking_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='registered_favorite_property',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
